"""
Django settings for use_django_db project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

#LANGUAGE_CODE='zh-Hans'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9n=#xdk4dbk0%6#@3tni1mct9ua=e73b7icjwe84k8vdm%rj^j'

# SECURITY WARNING: don't run with debug turned on in production!



# Application definition

INSTALLED_APPS = [
    'match_stat',
]
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''

DATABASES = {

    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_web',
        'USER':'django_admin',
        'PASSWORD':'123456',
        'HOST':'localhost',
        'PORT':'',
        #'OPTIONS': {#'charset': 'utf8mb4','init_command':
        #    "SET sql_mode='STRICT_TRANS_TABLES'"},
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
